### ISSUE TITLE
Topre Pad footprint connections

### ISSUE THREAD

**Issue by myreauks** [tomsmalley/custom-topre-guide#1]
Hi!

First of all, thanks for the comprehensive guide and the vast background research that has gone into it. One thing that was left a bit unclear for me are the connections on the KiCad file for the Topre pad. There are three connections: 

S(Input)
R(Output)
G(Power Input)

Which one of these is the analog signal to connect to the analog multiplexer? And which one goes to ground? The way I figured was that the Input pin goes to the multiplexer, the output pin to ground and the Power Input to the StrobePin. Is this correct?

Thanks!

**Comment by tomsmalley** [comment]
It's so long since I designed it that I'm not sure :)

Just ensure that one "D" is the strobe line and the other "D" is the read line (mux), and the strip which separates them is ground. The ground pour should merge with the central line when you go to the layout view.

**Comment by myreauks** [comment]
Thanks for the fast answer!
That makes sense, I think I can go forward with this knowledge.
